# Generated by Django 4.1 on 2023-12-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use_Miso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Used_Miso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('thoughts', models.TextField()),
                ('taste_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('appearance_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
            ],
        ),
    ]
