# Generated by Django 4.1 on 2023-12-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_use_miso_used_miso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('use_miso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.use_miso')),
                ('used_miso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.used_miso')),
            ],
        ),
    ]
