# Generated by Django 4.1 on 2023-12-20 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='use_miso',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='used_miso',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='use_miso',
            name='image',
            field=models.ImageField(upload_to='use_miso_images/'),
        ),
        migrations.AlterField(
            model_name='used_miso',
            name='image',
            field=models.ImageField(upload_to='used_miso_images/'),
        ),
    ]
