# Generated by Django 4.1 on 2023-12-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_product_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_miso',
            name='used_miso',
            field=models.BooleanField(default=False),
        ),
    ]
