# Generated by Django 4.1 on 2024-01-01 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_used_miso_used_miso'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_miso',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_used_misos', to=settings.AUTH_USER_MODEL),
        ),
    ]
